name: Workflow 1

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    
    runs-on: windows-latest

    steps:
      - name: Test Step
        run: echo "Hello World"
      - name: Test Step (1)
        run: npm --version
      - name: Test Step (2)
        run: node --version
